version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      container_name: my-fastapi-app
    depends_on:
      - db
    ports:
      - 8081:8000