apiVersion: apps/v1
kind: Deployment
metadata:
  name: textflow-auth
  labels:
    app: textflow-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textflow-auth
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: textflow-auth
    spec:
      containers:
        - name: textflow-auth
          image: devhack95/textflow-auth:1.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret