apiVersion: v1
kind: Service
metadata:
  name: textflow-auth
spec:
  selector:
    app: textflow-auth
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30007